---
- name: update slackpkg GPG key
  ansible.builtin.command: "/usr/sbin/slackpkg -batch=on update gpg"
  changed_when: False

- name: update slackpkg
  ansible.builtin.command: "/usr/sbin/slackpkg -batch=on -default_answer=y update"
  changed_when: False
